spring:
  datasource:
    url: jdbc:mysql://39.108.236.167:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Root123..
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 10
    #用来检测连接是否有效的sql，要求是一个查询语句 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: SELECT '1' FROM DUAL
    # 使用ali数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    pay:
      host: 39.108.236.167
      port: 5672
      username: admin
      password: admin
      virtual-host: demo-mq
    host: 39.108.236.167
    port: 5672
    username: admin
    password: admin
    virtual-host: demo-mq
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    #开启发送失败退回
    publisher-returns: true
    #开启ack
    listener:
      simple:
        acknowledge-mode: manual
    prefetchCount: 50
    maxConcurrentConsumers: 10
    concurrentConsumers: 10
    autoStartup: true
eureka:
  user:
    name: admin  # 用户名
    password: root123   # 用户密码
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@39.108.236.167:9090/eureka
feign:
  client:
    config: # 此配置在FeignClientFactoryBean中使用
      default:
        connectTimeout: 1000 # 连接超时时间
        readTimeout: 4000    # 处理超时时间
        loggerLevel: NONE    # 日志级别，NONE, 不记录日志 (默认)，BASIC, 只记录请求方法和URL以及响应状态代码和执行时间。HEADERS, 记录请求和应答的头的基本信息。FULL, 记录请求和响应的头信息，正文和元数据。
  httpclient:
    enabled: true # FeignRibbonClientAutoConfiguration 和 HttpClientFeignLoadBalancedConfiguration
    maxConnections: 200 # 最大连接数，默认值200
    maxConnectionsPerRoute: 50 # 每个host最大使用连接数，默认值50
    connectionTimeout: 2001 # 连接超时时间，默认值2000
    connectionTimerRepeat: 3000 #默认值3000
    #timeToLive: 900 # 默认存活时间900秒
    #timeToLiveUnit: SECONDS # 存活时间单位，默认秒
    #followRedirects: true
  hystrix:
    enabled: true  # 来源 HystrixFeignConfiguration
# Hystrix断路参数配置
# 超时参数不需要配置，不配置时为0，计算httpclient的超时时间并使用
hystrix:
  command:
    default: #default时为默认配置, 相关参数说明在 HystrixCommandProperties
      fallback:
        enabled: false # 关闭fallback功能（默认值为true）
      execution:
        isolation:
          strategy: SEMAPHORE # 默认使用线程池隔离，建议改用SEMAPHORE
          semaphore:
            maxConcurrentRequests: 300
          thread:
            timeoutInMilliseconds: 5000 # 设置超时时间(默认值为1000)
  #    UserApiClient#list(User,Integer,Integer):
  #      execution:
  #        isolation:
  #          thread:
  #            timeoutInMilliseconds: 5002
  #线程池隔离策略时，线程池参数配置
  threadpool:
    default: #默认配置，单独配置时改为serverId
      allowMaximumSizeToDivergeFromCoreSize: true #是否允许coreSize扩展到maximumSize，为false时仅coreSize生效，相当于FixedThreadPool
      coreSize: 30
      maximumSize: 50
      keepAliveTimeMinutes: 60
      maxQueueSize: 200

# Feign 中Ribbon 相关逻辑，请查看LoadBalancerFeignClient
# {serverId}: 添加本层时，单独配置某一serverId的httpClient参数，相关参数参考 CommonClientConfigKey 只适用于zuul
ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 1000
  MaxTotalConnections: 1000 #连接池最大连接数
  MaxConnectionsPerHost: 50 #每个host最大使用连接数
  OkToRetryOnAllOperations: true
  # 在使用过程中，一般会对超时时间、线程池大小、信号量等进行修改，具体要结合业务进行分析、默认Hystrix的超时时间为1秒，但在实际的运用过程中，发现1秒有些过短，通常会设置为5~10秒左右，
  # 如果配置了Ribbon的时间，其超时时间也需要和Hystrix的时间配合使用，一般情况下Ribbon的时间应短于Hystrix超时时间。
  eager-load:
    # 为了解决第一次访问慢问题
    enabled: true
    clients: demo-management-service