package com.suixingpay.core.mapper;

import com.suixingpay.core.domain.Phone;

import java.util.List;

public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    int insertSelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    Phone selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    int updateByPrimaryKeySelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Sun Oct 13 17:19:00 CST 2019
     */
    int updateByPrimaryKey(Phone record);

    /**
     * 根据条件查询
     * @param phone
     * @return
     */
    List<Phone> selectByContent(Phone phone);

    /**
     * 统计条数
     * @param phone
     * @return
     */
    int countByContent(Phone phone);
}